CREATE TABLE "afk_status" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "afk_status_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"jid" text NOT NULL,
	"reason" text NOT NULL,
	"time" timestamp with time zone NOT NULL,
	CONSTRAINT "afk_status_jid_unique" UNIQUE("jid")
);
